<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title><xsl:value-of select="/rss/channel/title"/> RSS Feed</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1000px;
            margin: 0 auto;
            padding: 2rem 1.25rem;
          }
          h1 {
            color: #1e3a8a;
            margin-top: 0;
          }
          h1 a {
            text-decoration: none;
            color: inherit;
          }
          h2 {
            margin-top: 2rem;
            margin-bottom: 0.5rem;
            color: #1e3a8a;
          }
          .header {
            padding-bottom: 1rem;
            margin-bottom: 2rem;
            border-bottom: 1px solid #eaeaea;
          }
          .header p {
            margin-top: 0.5rem;
            color: #666;
          }
          .feed-item {
            margin-bottom: 2rem;
            padding-bottom: 1rem;
            border-bottom: 1px solid #eaeaea;
          }
          .feed-item:last-child {
            border-bottom: none;
          }
          .feed-item h2 a {
            text-decoration: none;
            color: #1e3a8a;
            font-weight: 600;
          }
          .feed-item h2 a:hover {
            text-decoration: underline;
          }
          .meta {
            color: #666;
            font-size: 0.875rem;
          }
          .meta span {
            margin-right: 1rem;
          }
          .button {
            display: inline-block;
            padding: 0.5rem 1rem;
            background-color: #1e3a8a;
            color: white;
            border-radius: 0.25rem;
            text-decoration: none;
            font-weight: 500;
            margin-top: 0.5rem;
          }
          .button:hover {
            background-color: #2d4ba0;
          }
          .footer {
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #eaeaea;
            color: #666;
            font-size: 0.875rem;
          }
          @media (max-width: 600px) {
            body {
              padding: 1rem;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1><a href="{/rss/channel/link}"><xsl:value-of select="/rss/channel/title"/></a></h1>
          <p><xsl:value-of select="/rss/channel/description"/></p>
          <a class="button" href="{/rss/channel/link}">Visit Website</a>
        </div>
        <div class="items">
          <xsl:for-each select="/rss/channel/item">
            <div class="feed-item">
              <h2><a href="{link}" target="_blank"><xsl:value-of select="title"/></a></h2>
              <div class="meta">
                <span>Published: <xsl:value-of select="pubDate"/></span>
                <xsl:if test="category">
                  <span>Categories: 
                    <xsl:for-each select="category">
                      <xsl:value-of select="."/><xsl:if test="position() != last()">, </xsl:if>
                    </xsl:for-each>
                  </span>
                </xsl:if>
              </div>
              <p><xsl:value-of select="description"/></p>
              <a class="button" href="{link}" target="_blank">Read More</a>
            </div>
          </xsl:for-each>
        </div>
        <div class="footer">
          <p>This RSS feed is generated by TrustyConvert. Subscribe to this feed to receive updates when new content is published.</p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 